#contains paths to indexed genome files! bowtie2 generated these files so ending in .bt2
#end the path with the prefix of the file names ending in .bt2

#fastq-screen config for Lrhopmboides bisulfite genome

#path to bismark
BISMARK /apps/x86-64/apps/spack_0.19.1/spack/opt/spack/linux-rocky8-zen3/gcc-11.3.0/bismark-0.23.0-co7pmcqwphg747asb55qqwokpl64ug6c/bin/bismark

#path to bowtie2 indexes, have to include in the line which aligned to use (bowtie2) and then : and then give the database a name (name doesnt matter)
DATABASE bowtie2:Lrhomboides /home/aubaxb001/genomes/Lrhomboides/Bowtie2
