#!/bin/bash
#PBS -N methylation_bias
#PBS -l walltime=10:00:00
#PBS -l select=1:ncpus=6:mem=500gb
#PBS -q bigmem
#PBS -o merge_lanes.o
#PBS -e merge_lanes.e
#PBS -M alb0293@auburn.edu
#PBS -m abe

# code modified from: https://github.com/ben-laufer/CpG_Me/blob/master/Paired-end/CpG_Me_PE_switch.sh

##############
# Initialize #
##############

# set mainPath
export mainPath="/home/aubaxb001/methylation_data"

# Command line arguments set the module and genome variables
# Provide a task_samples.txt file of sample ids (no file extensions) with one per a line in working directory and a raw_sequences folder with paired fastq files (.fq.gz)

#this allows you to run different parts of the script without running the whole thing! ex if you just want to run the trimming block (ends with ;;) you would run ./methyl_bias.sh trim to just do the trimming step
module=$1

################
# Load Modules #
################

#module load bismark/0.23.0
#module load bowtie2/2.4.2
#module load samtools/1.18
#module load fastq-screen/0.15.3
#module load picard/2.26.2
#module load trimgalore/0.6.7
#load anaconda to be able to use cutadapt - cutadapt is included in anaconda so if anaconda is loaded, cutadapt will work
#module load anaconda/3-2020.02

######################
# Set Up Environment #
######################

#make variable to go to sample directories
directory="/home/aubaxb001/methylation_data/"

#make variable for path to bisulfite converted genomes
genome_dir="/home/aubaxb001/genomes/Lrhomboides/"

#variable to go to the directory where the merged lane files are
rawpath=${directory}${sample}/

#make variable for path to each sample in the methylation_data dir, all output files will be placed in that samples dir
output=${rawpath}

#path to coverage file generated by bismark, will contain per CpG site methylation coverage info, important!!
#cov=${sample}_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz

#################
# Case Switches #
#################

case ${module} in
     trim)
          ########
          # Trim #
          ########

	#path to where the merged lane files are - theyre in trimmed directory
	trimmed_path="/home/aubaxb001/methylation_data/trimmed/"
	cd "${trimmed_path}"

	#loop through R1 and R2 fastq files
	for fastq1 in *_1.fq.gz; do
	        prefix="${fastq1%_1.fq.gz}"
        	fastq2="${prefix}_2.fq.gz"

	#make sure R2 file exists
        	if [[ ! -f "$fastq2" ]]; then
                	echo "Warning: $fastq2 not found, skipping sample $prefix"
                	continue
        	fi

        echo "Trimming sample: ${prefix}"
        echo "Read1: ${fastq1}"
        echo "Read2: ${fastq2}"

          # trimming! paired end input files, use 2 cores, quality cutoff of 20 (check this)
		#clip_r* = remove the first 10 bases from 5' end of read 1/2, this is avoiding the methylation bias!, remove first 20 bases from 5 end
		#remove 10 bases from 3' end of both reads
		#specify output directory, made specific directory for trimmed reads
		#got rid of fastqc step since the installed version of trim_galore doesnt have access to it, since i have a qc later in the pipeline its okay
        	#used NovaSeq platform according to novogene quote so include --2colour line, might not be needed for other sequencing platforms  
		#adapter sequences from Novogene - had them check to make sure I was going to use the right ones
		#following this website for trimming parameters: https://felixkrueger.github.io/Bismark/bismark/library_types/
			#used the Accel NGS Swift Bio kit
	call="trim_galore \
          --paired \
          --cores 2 \
          --2colour 20 \
          --clip_r1 10 \
          --clip_r2 15 \
          --three_prime_clip_r1 10 \
          --three_prime_clip_r2 10 \
	  --adapter GATCGGAAGAGCACACGTCTGAACTCCAGTCAC \
	  --adapter2 AGATCGGAAGAGCGTCGTGTAGGGAAAGA \
          --output_dir ${trimmed_path} \
          ${fastq1} \
          ${fastq2}"

          echo ${call}
          eval ${call}

	done
          ;;

     align)
          ##########
          # Screen #
          ##########
		#i dont know if this block works the way it is now - i ended up making individual scripts per sample to make the process go faster
		#run fastq_screen and bismark on trimmed paired-end Fastq files - screen for contamination and then bismark to align the reads to bisulfite genome
		#want to work in the directory that contains the trimmed files
		trimmed_path="/home/aubaxb001/methylation_data/trimmed"
		cd ${trimmed_path}
	echo "trimmed path: ${trimmed_path}"
	echo "genome directory: ${genome_dir}"

		#same loop as before to go through all of the sample directories
		 for trim1 in *_1_val_1.fq.gz; do

		[[ -e "$trim1" ]] || continue
			base="${trim1%_1_val_1.fq.gz}"
			trim2="${base}_2_val_2.fq.gz"
		if [[ ! -f "/home/aubaxb001/methylation_data/trimmed/${trim2}" ]]; then
			echo "Warning: paired end file for $trim1 not found - skipping"
			continue
		fi
		echo "Processing sample: $base"

          call="cd ~ && fastq_screen \
	  --conf /home/aubaxb001/fastq_screen.conf \
          --bisulfite \
          ${trimmed_path}/${trim1} \
          ${trimmed_path}/${trim2}"

          echo "Running: ${call}"
          eval ${call}

          #########
          # Align #
          ########

		echo "past fastqscreen"

		#n=1 allows for 1 mismatch

          call="cd ~ && bismark \
          -n 1 \
          --genome "${genome_dir}" \
          -1 "${trimmed_path}/${trim1}" \
          -2 "${trimmed_path}/${trim2}""

          echo "Running: ${call}"
          eval ${call}

	done
	echo "Aligning complete"
	;;

	 deduplicate)
          #########################
          # Remove PCR Duplicates #
          #########################

		#want to be in the directory where the bam files are, they were output into the trimmed_path through the align step above
		trimmed_path="/home/aubaxb001/methylation_data/trimmed"	
		cd ${trimmed_path}

		echo "Current directory: $(pwd)"
		echo "Looking for BAM files:"
		ls *_val_1_bismark_bt2_pe.bam
		#there is 1 .bam file per sample ending with "_1_val_1_bismark_bt2_pe.bam"
	          # WGBS only - dont have to do this if did not do WGBS
		#options in deduplicate call: bam = indicating input file is in bam format, paired = paired end reads
		#make loop to go through all .bam files in the trimmed directory
	for bamfile in *_val_1_bismark_bt2_pe.bam; do
		echo "Processing ${bamfile}..."

          call="deduplicate_bismark \
          --bam \
          --paired \
          "${bamfile}""

          echo "Running ${call}"
          eval ${call}
echo "Finished processing ${bamfile}"
echo "------------------------------"

#end the loop
done
          ;;

     insert)
     	  #######################
     	  # Insert Size Metrics #
     	  #######################

		#stay here since this is where the bam files are and now the deduplicated bam files too
	trimmed_path="/home/aubaxb001/methylation_data/trimmed"
     	  cd ${trimmed_path}

		#sort the deduplicated bam file by coordinate, need coordinate sorted bam files for downstream analysis
		#coordinate is a tool from picard so can look at manual if want to change that sorting
		#then going to calculate the distribution of the insert sizes for QC

		#loop through each deduplicated bam file
	for bam in *_1_val_1_bismark_bt2_pe.deduplicated.bam; do
		echo "Processing $bam"
	#build names for output without the .bam
	base="${bam%.bam}"
	#need R to generate the histogram so load that in along with picard if you want the histogram to be generated
	#output file names
	sortedBAM="${base}_sorted.bam"
	insert="${base}_insert_size_metrics.txt"
	histogram="${base}_insert_size_histogram.pdf"

		#sort the BAM file
     	  call="picard SortSam \
		  INPUT=${bam} \
		  OUTPUT=${sortedBAM} \
		  SORT_ORDER=coordinate"

		  echo "${call}"
		  eval ${call}

			#collect insert size metrics
		  call="picard CollectInsertSizeMetrics \
		  INPUT=${sortedBAM} \
		  OUTPUT=${insert} \
		  Histogram_FILE=${histogram} \
		  ASSUME_SORTED=TRUE"

		  echo "${call}"
		  eval ${call}

#end the loop
done
     	  ;;

     coverage)
          #######################
          # Nucleotide Coverage #
          #######################
                #tool for calculating nucleotide coverage from bam files, will give summary of nucleotide coverage metrics
		#counts how many times each nucleotide appears in the aligned reads - helps assess base composition AFTER alignment, biases, coverage of cytosines
		#kind of QC step

		#this is using Bismark (also requires samtools but samtools is loaded in when bismark is loaded in)

		#want to be in trimmed_path still, this is where deduplicated_sorted.bam files are
		trimmed_path="/home/aubaxb001/methylation_data/trimmed"
          cd ${trimmed_path}

		#want to point to ref genome fasta files for the genome folder option in bam2nuc
		genome_dir="/home/aubaxb001/genomes/Lrhomboides"

		#loop through all samples - want to use the sorted, deduplicated file so *_deduplicated_sorted.bam
		for bamfile in *.deduplicated_sorted.bam; do
		ls -l *.deduplicated_sorted.bam
                echo "Processing ${bamfile}..."
		echo "Found BAM: ${bamfile}"

	#output dir will be where I am so will output files intro trimmed dir
          call="bam2nuc \
          --genome_folder ${genome_dir} \
          ${bamfile}"

          echo "${call}"
          eval "${call}"
#end the loop
done
          ;;

     extract)
          #######################
          # Extract Methylation #
          #######################
	#this is going to extract methylation data from the deduplicated bam files

		#stay in trimmed path to continue!
	trimmed_path="/home/aubaxb001/methylation_data/trimmed"
          cd ${trimmed_path}

                #loop through all samples - want to use the UNsorted, deduplicated file - methylation extractor doesnt want sorted files
                for bamfile in *.deduplicated.bam; do
                echo "Processing ${bamfile}..."

		#paired end reads, zip output files to make them .gz format
		#default = no overlap of R1 and R2
		#--comprehensive: merge all 4 possible strand specific methylation info into context dependent output files - default contexts are CpG, CHG, CHH
			#--merge_non_CpG: produce 2 output files for Cs in CpG context and non-CpG context
		#--bedGraph: write output into sorted benGraph file that reports the position of a given C and its methylation state - only Cs in CpG context will be sorted
		#--buffer_size: specify main memory sort buffer when sorting the methylation info
          	call="bismark_methylation_extractor \
          	--paired-end \
          	--gzip \
          	--comprehensive \
          	--merge_non_CpG \
          	--bedGraph \
          	--multicore 6 \
          	--buffer_size 34G \
          	${bamfile}"

          	echo "${call}"
          	eval ${call}

#end the loop
done
          ;;

     cytosineReport)
          ###################
          # Cytosine Report #
          ###################
		#this block is going to convert coverage data from bismark methylation extractor into a genome wide cytosine report
		#this is generating a cytosdine methylation report and a sorted methylation input file is used
		#sorted file is the .cov.gz file generated from the previous block (need to use the bedGraph option to get the right input file
			#sorted by position
	#stay in the same directory
		trimmed_path="/home/aubaxb001/methylation_data/trimmed"
		cd ${trimmed_path}

		#path to genome directory with fasta files
		genome_dir="/home/aubaxb001/genomes/Lrhomboides"
	#loop through all files - want to use .cov.gz as input file which was generated from the step above
	for cov in *.bismark.cov.gz; do
                echo "Processing ${cov}..."
		#extract sample name and remove .bismark.cov.gz
		sample="${cov%.bismark.cov.gz}"

		#output file is cov variable generated above,
		#genome folder should be directed to the FASTA files NOT .bt2 files
		#compress the output file into .gz format
		#merge CpG sites into a single output entry (might not want to do this?)
		#specify the input coverage file
		#the only thing i cahnged was the naming convention for fthe output file SO the structure of the ouput file is the same (and doesnt have to be changed for DMRichR but the naming is just different)
          call="coverage2cytosine \
          --output ${trimmed_path}/${sample}_cytosine_report \
          --genome_folder ${genome_dir}/ \
          --gzip \
          --merge_CpG \
          ${trimmed_path}/${cov}"

          echo ${call}
          eval ${call}

          #############
          # QC Report #
          #############
		#this block is going to generate qc .html reports
#make new directory for these for organization purposes
#mkdir -p finalQC

          call="bismark2report --dir finalQC"

          echo ${call}
          eval ${call}

#end the loop
done
          ;;

#end case block in its entirity

     *)
          echo "Error: Pipeline case selection of ${module} is invalid or not specified."
          echo "Please select either trim, align, deduplicate, insert, coverage, extract, or cytosineReport"
          ;;
esac
